name: smart_task_app
description: "A Smart Site Task Manager that automatically classifies and prioritizes tasks using AI logic."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter


  # UI & Assets
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  intl: ^0.20.2

  # State Management
  provider: ^6.1.5

  # Networking
  dio: ^5.9.0
  connectivity_plus: ^7.0.0

  # Security & Config
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets section must match your folder structure
  assets:
    - assets/.env